name: build

on:
  push:
    branches: [ main ]
    paths: ['**/*.go', '.github/workflows/*.yml', '**/*.toml'] # goファイル, ymlファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.23.x, 1.22.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Build
        run: go build -ldflags="-s -w"