name: build

on:
  push:
    branches: [ main ]
    paths: ['**/*.go', '.github/workflows/*.yml', '**/*.toml'] # goファイル, ymlファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Build
        run: go build -v main.go

  test:
    needs: build

    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Test
        run: go test -v .

  benchmark:
    needs: build

    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Benchmark
        run:  go test -bench . -benchmem