name: build

on:
  push:
    branches: [ main ]
    paths: ['**/*.go', '.github/workflows/*.yml', '**/*.toml'] # goファイル, ymlファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SLACK_USERNAME: ci failure notification
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Build
        run: go build -v main.go

      - name: Slack Failure Notification on Build
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_TITLE: steps commit name "${{github.event.head_commit.message}}"
          SLACK_COLOR: danger
          SLACK_MESSAGE: steps build failed!!!

  test:
    needs: build

    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Test
        run: go test -v .

      - name: Go Benchmark
        run:  go test -bench . -benchmem

      - name: Slack Failure Notification test 
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: steps commit name "${{github.event.head_commit.message}}"
            SLACK_COLOR: danger
            SLACK_MESSAGE: steps test failed!!!

  benchmark:
    needs: build

    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Benchmark
        run:  go test -bench . -benchmem

      - name: Slack Failure Notification benchmark
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: steps commit name "${{github.event.head_commit.message}}"
            SLACK_COLOR: danger
            SLACK_MESSAGE: steps benchmark failed!!