name: lint

on:
  push:
    branches: [ main ]
    paths: ['**/*.go', '.github/workflows/*.yml', '**/*.toml'] # goファイル, ymlファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    strategy:
      matrix:
        go-versions: [1.20.0, 1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]

    permissions:
      checks: write
      contents: read

    timeout-minutes: 5

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: ${{matrix.go-versions}}

          # reviewdog の動作モードの指定
          reporter: github-check

          github_token: ${{github.token}}

          filter_mode: nofilter

          #このファイルパスにgolangciの設定ymlファイルをおく
          golangci_lint_flags: "--config=.github/.golangci.toml"

          # Github Status へのレポートレベルの指定
          level: warning