package view

import (

)

var fileTypeList map[string]string = map[string]string{
	".c":  "C",
	".h":  "C",
	".cpp": "C++",
	".cc":  "C++",
	".hpp": "C++",
	".cs": "C#",
	".html": "HTML",
	".css": "CSS",
	".scss": "SCSS",
	".sass": "SASS",
	".py": "Python",
	".java": "Java",
	".js": "JavaScript",
	".ts": "TypeScript",
	".rb": "Ruby",
	".go": "Go",
	".php": "PHP",
	".xml": "XML",
	".json": "JSON",
	".yaml": "YAML",
	".yml": "YAML",
	".md": "Markdown",
	".txt": "Plain Text",
	".sql": "SQL",
	".sh": "Shell Script",
	".bat": "Batch File",
	".pl": "Perl",
	".swift": "Swift",
	".r": "R",
	".scala": "Scala",
	".kt": "Kotlin",
	".dart": "Dart",
	".asm": "Assembly",
	".lua": "Lua",
	".clj": "Clojure",
	".coffee": "CoffeeScript",
	".f90": "Fortran",
	".groovy": "Groovy",
	".v": "Verilog",
	".vhdl": "VHDL",
	".d": "D",
	".nim": "Nim",
	".pas": "Pascal",
	".tcl": "Tcl",
	".raku": "Raku",
	".erl": "Erlang",
	".ex": "Elixir",
	".exs": "Elixir Script",
	".fs": "F#",
	".ml": "ML",
	".m": "Objective-C",
	".s": "Assembly",
	".xsl": "XSLT",
	".less": "Less",
	".log": "Log File",
	".ini": "Initialization File",
	".cfg": "Configuration File",
	".rtf": "Rich Text Format",
	".doc": "Microsoft Word Document",
	".docx": "Microsoft Word Document (Open XML)",
	".pdf": "Portable Document Format",
	".epub": "Electronic Publication",
}